services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

  producer:
    build:
      context: ./src/InventoryProducer
      dockerfile: Dockerfile
    working_dir: /app/producer
    command: ["dotnet", "InventoryProducer.dll"]
    ports:
      - "5001:80"
  
  consumer:
    build:
      context: ./src/InventoryConsumer
      dockerfile: Dockerfile
    working_dir: /app/consumer
    command: ["dotnet", "InventoryConsumer.dll"]
    ports:
      - "5002:80"
